import subprocess
import sys
from pathlib import Path

import pytest

from tests.utils import GitDir
from version_builder import main


class TestMain:
    def test_cpp_source_git(self, tmp_path):
        git_dir = GitDir(tmp_path)
        git_dir.commit()
        git_dir.tag("v1.0.0-alpha.1")
        main.create_version_file(
            source="git",
            source_input=git_dir.path,
            output_file=git_dir.path / "version.hpp",
            lang="cpp",
        )
        assert (git_dir.path / "version.hpp").exists()
        assert Path.stat(git_dir.path / "version.hpp").st_size != 0

    def test_cpp_source_git_nested_include(self, tmp_path):
        git_dir = GitDir(tmp_path)
        git_dir.commit()
        git_dir.tag("v1.0.0-alpha.1")
        optional_config = main.OptionalConfiguration()
        optional_config.namespace = "plxsversion::version"

        # Nested include dirtory
        main.create_version_file(
            source="git",
            source_input=git_dir.path,
            output_file=git_dir.path / "version.hpp",
            lang="cpp",
            optional_config=optional_config,
        )
        assert (git_dir.path / "plxversion/version/version.hpp").exists()
        assert Path.stat(git_dir.path / "plxversion/version/version.hpp").st_size != 0

    def test_cpp_source_file(self, tmp_path):
        git_dir = GitDir(tmp_path)
        file = git_dir.path / "version.txt"
        file.write_text("1.1.0-beta.2+build.meta")  # More complex SemVer from file
        git_dir.add_all()
        git_dir.commit()
        # The git tag is mostly for git context here, version comes from file
        main.create_version_file(
            source="file",
            source_input=file,
            output_file=git_dir.path / "version.hpp",
            lang="cpp",
        )
        assert (git_dir.path / "version.hpp").exists()
        assert Path.stat(git_dir.path / "version.hpp").st_size != 0

    def test_print_file(self, tmp_path, capsys):
        git_dir = GitDir(tmp_path)
        git_dir.commit()
        git_dir.tag("v0.1.0-rc.1")
        optional_config = main.OptionalConfiguration(print_created_file=True)
        main.create_version_file(
            source="git",
            source_input=git_dir.path,
            output_file=git_dir.path / "version.hpp",
            lang="cpp",
            optional_config=optional_config,
        )
        captured = capsys.readouterr()
        assert "This file is autogenerated." in captured.out

    def test_cpp(self, tmp_path):
        git_dir = GitDir(tmp_path)
        git_dir.commit()
        git_dir.tag("v1.0.0")
        with pytest.raises(ValueError, match="Unexpected file ending for lang"):
            # incorrect version file extension
            main.create_version_file(
                source="git",
                source_input=git_dir.path,
                output_file=git_dir.path / "version.h",
                lang="cpp",
            )

    def test_c(self, tmp_path):
        git_dir = GitDir(tmp_path)
        git_dir.commit()
        git_dir.tag("v1.0.0")
        with pytest.raises(ValueError, match="Unexpected file ending for lang"):
            # incorrect version file extension
            main.create_version_file(
                source="git",
                source_input=git_dir.path,
                output_file=git_dir.path / "version.hpp",
                lang="c",
            )
        main.create_version_file(
            source="git",
            source_input=git_dir.path,
            output_file=git_dir.path / "version.h",
            lang="c",
        )
        assert (git_dir.path / "version.h").exists()
        assert Path.stat(git_dir.path / "version.h").st_size != 0

    def test_cpp11(self, tmp_path):
        git_dir = GitDir(tmp_path)
        git_dir.commit()
        git_dir.tag("v1.0.0")
        with pytest.raises(ValueError, match="Unexpected file ending for lang"):
            # incorrect version file extension
            main.create_version_file(
                source="git",
                source_input=git_dir.path,
                output_file=git_dir.path / "version.h",
                lang="cpp11",
            )
        main.create_version_file(
            source="git",
            source_input=git_dir.path,
            output_file=git_dir.path / "version.hpp",
            lang="cpp11",
        )
        assert (git_dir.path / "version.hpp").exists()
        assert Path.stat(git_dir.path / "version.hpp").st_size != 0

    def test_rust(self, tmp_path):
        git_dir = GitDir(tmp_path)
        git_dir.commit()
        git_dir.tag("v1.0.0")
        with pytest.raises(ValueError, match="Unexpected file ending for lang"):
            # incorrect version file extension
            main.create_version_file(
                source="git",
                source_input=git_dir.path,
                output_file=git_dir.path / "version.hpp",
                lang="rust",
            )
        main.create_version_file(
            source="git",
            source_input=git_dir.path,
            output_file=git_dir.path / "version.rs",
            lang="rust",
        )
        assert (git_dir.path / "version.rs").exists()
        assert Path.stat(git_dir.path / "version.rs").st_size != 0


class TestModuleInterface:
    def test_module_call(self, tmp_path):
        git_dir = GitDir(tmp_path)
        git_dir.commit()
        git_dir.tag("v2.0.0-final+build.123")
        subprocess.check_call(
            [
                sys.executable,
                "-m",
                "version_builder",
                "--lang",
                "cpp",
                "--source",
                "git",
                "--input",
                git_dir.path,
                git_dir.path / "version.hpp",
                "--print",
                "--time",
            ],
            env={"PYTHONPATH": Path.cwd() / "src"},
        )
        assert Path.exists(git_dir.path / "version.hpp")
        assert Path.stat(git_dir.path / "version.hpp").st_size != 0

    def test_cargo_version_rust(self, tmp_path):
        git_dir = GitDir(tmp_path)
        git_dir.commit()
        git_dir.tag("v2.0.0-final+build.123")
        subprocess.check_call(
            [
                sys.executable,
                "-m",
                "version_builder",
                "--lang",
                "rust",
                "--source",
                "git",
                "--input",
                git_dir.path,
                git_dir.path / "version.rs",
                "--cargo",
                "0.0.1",
            ],
            env={"PYTHONPATH": Path.cwd() / "src"},
        )
        assert Path.exists(git_dir.path / "version.rs")
        assert Path.stat(git_dir.path / "version.rs").st_size != 0

    def test_cargo_version_cpp(self, tmp_path):
        git_dir = GitDir(tmp_path)
        git_dir.commit()
        git_dir.tag("v2.0.0-final+build.123")
        with pytest.raises(subprocess.CalledProcessError):
            subprocess.check_call(
                [
                    sys.executable,
                    "-m",
                    "version_builder",
                    "--lang",
                    "cpp",
                    "--source",
                    "git",
                    "--input",
                    git_dir.path,
                    git_dir.path / "version.rs",
                    "--cargo",
                    "0.0.1",
                ],
                env={"PYTHONPATH": Path.cwd() / "src"},
            )

    def test_namespace_requires_cpp(self, tmp_path):
        git_dir = GitDir(tmp_path)
        git_dir.commit()
        git_dir.tag("v2.0.0")
        with pytest.raises(subprocess.CalledProcessError):
            subprocess.check_call(
                [
                    sys.executable,
                    "-m",
                    "version_builder",
                    "--lang",
                    "c",
                    "--namespace",
                    "my_namespace",
                    "--source",
                    "git",
                    "--input",
                    git_dir.path,
                    git_dir.path / "version.h",
                ],
                env={"PYTHONPATH": Path.cwd() / "src"},
            )

    def test_cli_default_namespace(self, tmp_path):
        git_dir = GitDir(tmp_path)
        git_dir.commit()
        git_dir.tag("v1.0.0")
        output_file = git_dir.path / "version.hpp"
        subprocess.check_call(
            [
                sys.executable,
                "-m",
                "version_builder",
                "--lang",
                "cpp",  # C++ lang
                # No --namespace flag
                "--source",
                "git",
                "--input",
                str(git_dir.path),
                str(output_file),
            ],
            env={"PYTHONPATH": str(Path.cwd() / "src")},
        )
        # Check that the default namespace was used
        content = output_file.read_text()
        assert "namespace plxsversion {" in content

        def test_cli_include_prefix_with_c(self, tmp_path):
            git_dir = GitDir(tmp_path)
            git_dir.commit()
            git_dir.tag("v1.0.0")
            output_dir = git_dir.path / "generated" / "include"
            output_file = output_dir / "version.h"
            subprocess.check_call(
                [
                    sys.executable,
                    "-m",
                    "version_builder",
                    "--lang",
                    "c",  # C lang
                    "--include-prefix",
                    "generated/include",
                    "--source",
                    "git",
                    "--input",
                    str(git_dir.path),
                    # The final arg is the output file path for the script to use
                    str(output_file),
                ],
                env={"PYTHONPATH": str(Path.cwd() / "src")},
            )
            assert output_file.exists()
            assert output_file.stat().st_size != 0

        def test_cli_empty_namespace_fails(self, tmp_path):
            git_dir = GitDir(tmp_path)
            git_dir.commit()
            git_dir.tag("v1.0.0")
            with pytest.raises(subprocess.CalledProcessError):
                subprocess.check_call(
                    [
                        sys.executable,
                        "-m",
                        "version_builder",
                        "--lang",
                        "cpp",
                        "--namespace",
                        "",  # Empty namespace
                        "--source",
                        "git",
                        "--input",
                        str(git_dir.path),
                        str(git_dir.path / "version.hpp"),
                    ],
                    env={"PYTHONPATH": str(Path.cwd() / "src")},
                )