[tool.ruff]
line-length = 120
exclude = [".git", ".vscode"]

[tool.ruff.lint]
# See https://docs.astral.sh/ruff/rules/
# TODO-KW: comment a why for our config options
select = ["A", "B", "BLE", "E", "F", "ISC", "ICN", "N", "PD", "RUF", "Q", "UP", "W" ]
# TODO-KW: many groups recommend enabling all and excluding manually. 
#select = ["ALL" ]
#ignore = [  ]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true