[tool.ruff]
line-length = 120
exclude = [".git", ".vscode"]

[tool.ruff.lint]
# See https://docs.astral.sh/ruff/rules/
select = ["ALL" ]
ignore = [ 
    "D203",     # prefer no blankline between class and docstring
    "D212",     # prefer summary on line after docstring opens
    "COM812",   # avoid unexpected behavior per ruff docs
    "S607",     # accept use of tools on path (such as git)


    "ANN", # TODO-KW: temp
    "D", # TODO-KW: temp

]

[tool.ruff.lint.per-file-ignores]
"*/tests/*" = [ 
    "S101",     # pytest uses asserts for testing
    "S603",     # unit tests should always control input to subprocesses
    "PLR2004",  # magic values for testing equality in unit testing is acceptable
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true