[tool.ruff]
line-length = 120
exclude = [".git", ".vscode"]

[tool.ruff.lint]
# See https://docs.astral.sh/ruff/rules/
select = ["ALL" ]
ignore = [ 
    "D203",     # prefer no blankline between class and docstring
    "D212",     # prefer summary on line after docstring opens
    "COM812",   # avoid unexpected behavior per ruff docs
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true